export const TASK_UPDATE_NAME = "TASK_UPDATE_NAME";
export const TASK_UPDATE_DESCRIPTION = "TASK_UPDATE_DESCRIPTION";
export const TASK_UPDATE_DEADLINE = "TASK_UPDATE_DEADLINE";
export const TASK_UPDATE_ATTACHMENT = "TASK_UPDATE_ATTACHMENT";
export const PIN_TASK = "PIN_TASK";
export const MOVE_TASK = "MOVE_TASK";

export const ADD_PIPELINE = "ADD_PIPELINE";
export const ADD_TASK_TO_PIPELINE = "ADD_TASK_TO_PIPELINE";
export const SORT_PIPELINE = "SORT_PIPELINE";
